### ISSUE TITLE
Text color should be accessible

### ISSUE THREAD

**Issue by kwge** [PredixDev/px-datetime-range-field#3]
The text color (css property) should be accessible by user.  The range picker maybe places in different theme where the background color maybe similar color as the "to" text string.  In this case, the "to" text string will not be visible to the user.  Please expose the css property for this field to allow individual theming.  
 
Here is the item:   <span class="caps u-mh-">to</span>

**Comment by benoitjchevalier** [comment]
Just added --px-datetime-range-field-to-color css variable to access this color in latest version (v0.3.11)
