### ISSUE TITLE
Date and time picker UI is not working. We have to enter date and time manually for this 

### ISSUE THREAD

**Issue by jvenky5885** [PredixDev/px-datetime-range-field#4]
We do not see the date picker  UI working for this px component. is there any plan to fix it?

-Venky

**Comment by benoitjchevalier** [comment]
Could you provide more information?

**Comment by nonmetalhail** [comment]
Hi,

Please check out our demo / catalog site where you can see the component working and you can play around with configuration options: http://predixdev.github.io/predix-ui/?show=px-datetime-range-field&type=component

If you are having issues configuring your component, please feel free to open a new issue, fill in the template, and provide a codepen demonstrating your issue and explain what you expect. I'd also suggest you give this a read for tips on asking a question with enough details that we can help: http://stackoverflow.com/help/how-to-ask
