### ISSUE TITLE
The word "TO" lacks NLS

### ISSUE THREAD

**Issue by navi2581** [PredixDev/px-datetime-range-field#7]
Hi,

In other locale, the word "TO" in the px-datetime-range-field lacks NLS. Could you please fix this.

![untitled](https://user-images.githubusercontent.com/3763703/36958313-db35fc00-2060-11e8-90cc-a1036c3ceed5.png)

**Comment by mdwragg** [comment]
Hi, what is NLS?

**Comment by navi2581** [comment]
NLS (localization/internationalization) - browser language

**Comment by mdwragg** [comment]
Never heard of it referred to as 'NLS'... I understand now.

'TO' is localisable like the other strings in px-datetime-range-field: https://github.com/PredixDev/px-datetime-range-field/blob/master/px-datetime-range-field.html#L73

See the guide here:
https://www.predix-ui.com/#/develop/internationalization
