### ISSUE TITLE
Missing behavior console errors

### ISSUE THREAD

**Issue by pbelch** [PredixDev/px-datetime-range-field#8]
Hi.

On installing the px-datetime-rage component, i am seeing the following errors in the browser console:

`Uncaught ReferenceError: pxDatetimeRangeBehavior is not defined (px-calendar-picker.html:99)`
`Uncaught ReferenceError: pxDatetimeBehavior is not defined (px-datetime-picker.html:124)`

I have tried several combinations of bower dependencies of the core components to resolve the issue but as of yet no joy.

Using the following bower resolutions:
`"px-datetime-common": "^3.0.0",
    "px-datetime-field": "^2.0.0"`

**Comment by katemenkhaus** [comment]
Hi pbelch, 
Are you installing the `px-datetime-range-field` or the `px-rangepicker`? The `px-datetime-range-field` doesn't reference `px-calendar-picker` or `px-datetime-picker`.  For that matter the `px-rangepicker` doesn't reference `px-datetime-picker` so I don't know how you'd have a referenceError with `px-datetime-picker` unless you're specifically using it. 
Those version are correct. Is there a reason that you have to use a resolution?

**Comment by pbelch** [comment]
I am using the `px-datetime-range-field`
` <px-datetime-range-field
                    required
                    allow-wrap
                    full-width
                    show-field-titles
                    block-past-dates
                    date-format="YYYY/MM/DD"
                    time-format="HH:mm"
                    time-zone="UTC"
                    show-time-zone="none"
                    min-date="2017-12-15T14:25:01.365Z"
                    max-date="2018-06-15T13:25:01.365Z"
                    from-moment="[[fromMoment]]"
                    to-moment="[[toMoment]]">
                  </px-datetime-range-field>`

I assumed that i was seeing those other components in the console was a result of the dependency on `px-datetime-common`?

I was seeing bower version conflicts on doing a bower install which was why the reason for the resolution. Bower.json file looks like this:
`
{
  "name": "ess-fe",
  "version": "1.0.9",
  "main": "index.html",
  "dependencies": {
    "polymer": "^1.9.0",
    "px-app-nav": "^2.1.3",
    "px-context-browser": "^2.0.4",
    "px-tabs": "^2.0.0",
    "px-key-value-pair": "^1.2.5",
    "px-card": "^1.0.4",
    "px-breadcrumbs": "^1.0.4",
    "px-inbox": "^2.0.2",
    "px-toggle": "^2.0.1",
    "px-data-table": "^4.0.4",
    "px-simple-bar-chart": "^2.1.1",
    "px-theme": "^3.0.0",
    "px-dark-theme": "^2.0.14",
    "px-dark-demo-theme": "^2.0.0",
    "px-gauge": "^2.0.2",
    "px-vis-timeseries": "^3.1.2",
    "px-vis-radar": "^3.1.1",
    "px-vis-polar": "^3.1.1",
    "px-popover": "^2.1.3",
    "px-modal": "https://github.com/PredixDev/px-modal.git#^3.2.1",
    "px-heatmap-grid": "^1.1.2",
    "app-route": "*",
    "px-datetime-range-field": "^2.2.1"
  },
  "resolutions": {
    "webcomponentsjs": "^0.7.0",
    "px-modal": "^2.0.4",
    "px-overlay": "^2.0.0",
    "px-datetime-common": "^3.0.0",
    "px-datetime-field": "^2.0.0"
  }
}
`

**Comment by randyaskin** [comment]
You shouldn't need any of the resolutions except for webcomponentsjs. Also make sure that you `rm -rf bower_components` before running `bower install` - especially if you have ever reverted to an earlier version of a component, but it's a good practice in general. The following installed cleanly for me with no bower conflicts:

```
{
  "name": "ess-fe",
  "version": "1.0.9",
  "main": "index.html",
  "dependencies": {
    "polymer": "^1.9.0",
    "px-app-nav": "^2.1.3",
    "px-context-browser": "^2.0.4",
    "px-tabs": "^2.0.0",
    "px-key-value-pair": "^1.2.5",
    "px-card": "^1.0.4",
    "px-breadcrumbs": "^1.0.4",
    "px-inbox": "^2.0.2",
    "px-toggle": "^2.0.1",
    "px-data-table": "^4.0.4",
    "px-simple-bar-chart": "^2.1.1",
    "px-theme": "^3.0.0",
    "px-dark-theme": "^2.0.14",
    "px-dark-demo-theme": "^2.0.0",
    "px-gauge": "^2.0.2",
    "px-vis-timeseries": "^3.1.2",
    "px-vis-radar": "^3.1.1",
    "px-vis-polar": "^3.1.1",
    "px-popover": "^2.1.3",
    "px-modal": "^3.2.1",
    "px-heatmap-grid": "^1.1.2",
    "app-route": "*",
    "px-datetime-range-field": "^2.2.1"
  },
  "resolutions": {
    "webcomponentsjs": "^0.7.0"
  }
}
```

**Comment by pbelch** [comment]
So seems it was an issues with `devDependencies`, as clean install still forced the resolution requests, but moving out some of px-components from there did the trick. Thanks :)
